package jre.bus;

public enum Station {
	PABT, 
	FOURTEENTHANDWILLOW, 
	FOURTEENTHANDWASHINGTON, 
	ELEVENTHANDWASHINGTON, 
	ELEVENTHANDWILLOW,
	ELEVENTHANDCLINTON, 
	FIFTHANDWASHINGTON, 
	FIFTHANDWILLOW, 
	FIFTHANDCLINTON, 
	FIRSTANDCLINTON, 
	FIRSTANDWILLOW,
	FIRSTANDWASHINGTON, 
	EIGTHENTHANDGROVE, 
	HAMILTONPARK,
	HOBOKENTERMINAL;
	
	Station() {
		
	}
}
